panel_bg_color: [0.007843138, 0.047058824, 0.11764706]
dock_layout:
  left_width: 280
  right_width: 280
  bottom_height: 200
  areas:
    left: [scene_hierarchy]
    left_active: 0
    right: [inspector]
    right_active: 0
    bottom: [console]
    bottom_active: 0
    floating: []
    floating_active: 0
  panel_visible:
    scene_hierarchy: true
    inspector: true
    console: false
  floating_positions:
    scene_hierarchy: [-77, 174]
    inspector: [1149, 171]
    console: [200, 200]