name: FeatureTest
startup_scene: assets://Scenes/Default.yaml
window:
  title: FeatureTest
  width: 1366
  height: 768
  fullscreen: false
  vsync: true
game_data_version: 1
plugins:
  - name: Spinner
    enabled: true
