Scene name: Default
Scene:
  - Entity: 0
    Name: Root
    Parent: 0
    TransformComponent:
      Position: [0, 0, 0]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    Children:
      - Entity: 1
        Name: "room\x00bject_0"
        Parent: 0
        TransformComponent:
          Position: [4.5, -0.5, 0.5]
          Rotation: [-3, -16, 150]
          Scale: [1, 1, 1]
        MeshComponent:
          MeshPath: Models\viking_room.obj
        RenderComponent:
          Visible: true
          Material: Materials\test1.material
        Children:
          - Entity: 2
            Name: "sub_room\x00t_0"
            Parent: 1
            TransformComponent:
              Position: [1.5, 0.5, -1]
              Rotation: [0, 172.5, 6.5]
              Scale: [1, 1, 1]
            MeshComponent:
              MeshPath: Models\DamagedHelmet\DamagedHelmet.gltf
            RenderComponent:
              Visible: true
              Material: Materials\test2.material
            Children:
              []
      - Entity: 3
        Name: Lantern
        Parent: 0
        TransformComponent:
          Position: [0, 0, 0]
          Rotation: [448.5, 297, 122.5]
          Scale: [1, 1, 1]
        LightComponent:
          LightEnabled: true
          LightType: 0
          LightColor: [0.9804642, 0.99509805, 0.9864899]
          LightIntencity: 0.838
          LightRadius: 1
          LightConeAngle: 2
        Children:
          []
      - Entity: 4
        Name: "ground\x00ect_0"
        Parent: 0
        TransformComponent:
          Position: [0, 0, -4]
          Rotation: [0, 0, 0]
          Scale: [10, 10, 1]
        MeshComponent:
          MeshPath: Models\Default\cube.obj
        RenderComponent:
          Visible: true
          Material: Materials\test3.material
        Children:
          []